### ISSUE TITLE
Add ability to return an empty spreadsheet with column names

### ISSUE THREAD

**Issue by mconlon17** [mconlon17/vivo-pump#104]
When `get` is asked to retrieve entities from a VIVO that does not have any, it should return an empty spreadsheet with column names ready for editing, and nrows = 0

Current implementation throws an exception:

    MacBook-Pro:mentoring mikeconlon$ python ../../sv.py -a get
    2015-09-25 09:15:50.696628 Start
    Traceback (most recent call last):
      File "../../sv.py", line 80, in <module>
        main()
      File "../../sv.py", line 60, in main
        n_rows = p.get()
      File "/Users/mikeconlon/PycharmProjects/vivo-pump/pump.py", line 126, in get
        return self.__do_get()
      File "/Users/mikeconlon/PycharmProjects/vivo-pump/pump.py", line 361, in __do_get
        write_csv(self.out_filename, sdata, delimiter=self.inter)
      File "/Users/mikeconlon/PycharmProjects/vivo-pump/vivopump.py", line 188, in write_csv
        f.write(delimiter.join(data[data.keys()[0]].keys()) + '\n')
    IndexError: list index out of range

**Comment by mconlon17** [comment]
Can't be done without completely restructuring the CSV data structure.  A major refactor.  Adding this item to future features and closing this issue for now.
